### ISSUE TITLE
Is tiny student training config correct?

### ISSUE THREAD

**Issue by ZJaume** [browsermt/students#5]
Hi,

I'm exploring the train-student directory to see if I can train student models for Paracrawl. I have taken a look at the training config file for tiny models  at https://github.com/browsermt/students/blob/master/train-student/models/student.tiny11/student.tiny11.yml and found options a bit confusing. The [paper](https://www.aclweb.org/anthology/2020.ngt-1.26.pdf) says tiny students use transformer encoder and rnn decoder but the config file is using: 
```yml
enc-cell: gru
enc-cell-depth: 1
enc-type: bidirectional
```
Maybe this options are ignored when using `type: transformer` but I wanted be sure it is the correct configuration before using it.

**Comment by snukky** [comment]
The important option is:

    transformer-decoder-autoreg: rnn

**Comment by kpu** [comment]
@snukky care to comment on the encoder part that he asked about?

**Comment by snukky** [comment]
Sorry, yes, the encoder options seem superfluous. The config has been extracted from a trained model.npz file, and because Marian .npz models store a predefined set of options regardless of model architecture, these options are just defaults.

Clarifying on the student architecture, the [WNGT 2019 paper](https://www.aclweb.org/anthology/D19-5632.pdf) describes it in more details. It has a modified *transformer* decoder with the self-attention block replaced by SSRU.

**Comment by ZJaume** [comment]
Alright, thanks for the clarification.
